eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/,http://localhost:9001/eureka/,http://localhost:9002/eureka/
# \u5BA2\u6237\u7AEF\u5237\u65B0\u670D\u52A1\u5217\u8868\u7F13\u5B58\u7684\u65F6\u95F4\u95F4\u9694
    registry-fetch-interval-seconds: 5
#ribbon:
#  ReadTimeout: 10000
#  ConnectTimeout: 10000

spring:
  application:
    name: eureka-consumer

server:
  port: 8060


eureka-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule